services:
  mongo:
    image: mongo:6.0
    container_name: mongo-container
    restart: unless-stopped
    volumes:
      - mongo-volume:/data/db
    networks:
      - project-network

  01_pms_server_service:
    build:
      context: ./Server
    container_name: 01_pms_server_compose_container
    restart: unless-stopped
    env_file:
      - ./Server/.env
    ports:
      - "4500:4500"
    depends_on:
      - mongo
    networks:
      - project-network

  01_pms_client_service:
    build:
      context: ./Client
      args:
        VITE_REACT_API_URL: http://localhost:4500
    container_name: 01_pms_client_compose_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - 01_pms_server_service
    networks:
      - project-network

volumes:
  mongo-volume:

networks:
  project-network:
    driver: bridge
