services:
  mongo:
    image: mongo:6.0
    container_name: mongo-container-pms
    restart: unless-stopped
    volumes:
      - mongo-volume:/data/db
    networks:
      - project-network

  01_pms_server_service:
    build:
      context: ./Server
    container_name: 01_pms_server_compose_container
    restart: unless-stopped
    env_file:
      - ./Server/.env
    
    depends_on:
      - mongo
    networks:
      - project-network

  01_pms_client_service:
    build:
      context: ./Client
      args:
        VITE_REACT_API_URL: "http://localhost/api"
    container_name: 01_pms_client_compose_container
    restart: unless-stopped
   
    depends_on:
      - 01_pms_server_service
    networks:
      - project-network


  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: unless-stopped 
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
        - "80:80"
    depends_on:
       - 01_pms_client_service
       - 01_pms_server_service
    networks:
    - project-network


volumes:
  mongo-volume:

networks:
  project-network:
    driver: bridge
