# simple reverse proxy configuration
# serves client at /
# proxcies requests to backend server at /api/*
# set the header  so that server can see original host and client

events{}

http{
    # to increase the client body size  to test load in the website 
    client_max_body_size 10M;

    server {
        listen 80;


        # when some one visit / or home page, it will for front services 
        location / {
            proxy_pass http://01_pms_client_compose_container:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;

        }
        location /api {
            proxy_pass http://01_pms_server_compose_container:4500;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-Proto $scheme;
            proxy_buffering off;
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;


        }
        location = /nginx-health {
            return 200 "ok";
            add_header Content-type text/plain;
        }
    }
}

